### ISSUE TITLE
Order of forename and initials?

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-ietf#100]
Having seen this example:

```
    name:
      given:
        forename:
        - language:
          - en
          script:
          - Latn
          initial: V
        - language:
          - en
          script:
          - Latn
          initial: G
        formatted_initials:
          content: V.G.
```

I have a question about the order of formatted initials and the name. `formatted_initials` field isn’t part of an array, so it’s unclear whether initials go before or after `forename`. 

For example, with names such as “Arthur C. Clarke” or “Iain M. Banks”, it’s clear that `formatted_initials` go _after_ `forename`. However, there are names where initials could equally go before the forename.

Does this mean we need to resort to `completename` in scenarios where the order of initials vs. forename matters?
