### ISSUE TITLE
Treating RFC organization authors as organizations

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#102]
As per https://github.com/ietf-tools/bibxml-service/issues/296#issuecomment-1273389794 request from the RPC, we are to distinguish the three classes of authors.

We will revert the change that introduced this:
- https://github.com/ietf-tools/relaton-data-rfcs/blob/742e255da9bdcec26907124a9660be2109fa8758/data/RFC3716.yaml#L25-L28

```yaml
  role:
  - description:
    - content: BibXML author
    type: author
```

## Type 1: Personal authors

No affiliation:
```xml
<author fullname="..." initials="..." surname="..."/>
```

```yaml
contributor:
- person:
    name:
      given:
        forename:
          initial: ...
          initial: ...
        formatted_initials:
          content: ...
      surname:
        content: ...
      completename:
        content: ...
```

With affiliation:
```xml
<author fullname="..." initials="..." surname="...">
  <organization>...</organization>
</author>
```

```yaml
contributor:
- person:
    name:
      given:
        forename:
          initial: ...
          initial: ...
        formatted_initials:
          content: ...
      surname:
        content: ...
      completename:
        content: ...
    affiliation: ...
```

## Type 2: Organizational authors

```xml
<author>
  <organization>...</organization>
</author>
```

```yaml
contributor:
- organization:
    name:
    - content: ...
```

## Type 3: Undetermined type authors

```xml
<author fullname="..."/>
```

```yaml
contributor:
- person:
    name:
      completename:
        content: ...
```

## List to categorize

The outcome of https://github.com/ietf-tools/bibxml-service/issues/296#issuecomment-1273456660 will determine the categorization of this list of authors which is filtered from the full rfc-index.xml (filtered away all personal names).

```
ACM SIGUCCS
Audio-Video Transport Working Group
Bolt Beranek
Defense Advanced Research Projects Agency
EARN Staff
ESCC X.500/X.400 Task Force
ESnet Site Coordinating Comittee (ESCC)
End-to-End Services Task Force
Energy Sciences Network (ESnet)
Federal Networking Council
Gateway Algorithms and Data Structures Task Force
IAB Advisory Committee
IAB and IESG
IAB
IANA
IESG
IETF Secretariat
ISO
ISOC Board of Trustees
Information Sciences Institute University of Southern California
International Organization for Standardization
International Telegraph and Telephone Consultative Committee of the International Telecommunication Union
Internet Activities Board
Internet Architecture Board
Internet Assigned Numbers Authority (IANA)
Internet Engineering Steering Group
KOI8-U Working Group
Mitra
National Bureau of Standards
National Research Council
National Science Foundation
NetBIOS Working Group in the Defense Advanced Research Projects Agency
Network Information Center. Stanford Research Institute
Network Technical Advisory Group
Newman Laboratories
North American Directory Forum
Sun Microsystems
The Internet Society
The North American Directory Forum
Vietnamese Standardization Working Group
```
