### ISSUE TITLE
`formatted_initials` without content

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-ietf#106]
So far noticed only in [draft-andersen-arc-01.yaml](https://github.com/ietf-tools/relaton-data-ids/blob/d082fe965553b16e509ed8007d712f39a1a8d2cf/data/draft-andersen-arc-01.yaml#L27-L39).

**Comment by ronaldtse** [comment]
There's not even a name inside this block:
```yaml
    name:
      given:
        formatted_initials:
          language:
          - en
      surname:
        content: None
        language:
        - en
      completename:
        content: None
        language:
        - en
```

**Comment by ronaldtse** [comment]
The root cause is this:

In the original RFC XML, there is an "author" that is an organization, not a person:
https://www.ietf.org/archive/id/draft-andersen-arc-01.xml

```xml
  <front>
    <title abbrev="ARC">Authenticated Received Chain (ARC)</title>

    <author initials="." surname="OAR-DEV Group">
      <organization>OAR-DEV Group</organization>
      <address>
        <email>arc-discuss@dmarc.org</email>
      </address>
    </author>
    <author initials="K." surname="Andersen" fullname="Kurt Andersen">
      <organization>LinkedIn</organization>
      <address>
        <postal>
          <street>2029 Stierlin Ct.</street>
          <city>Mountain View</city>
          <region>California</region>
          <code>94043</code>
          <country>USA</country>
        </postal>
        <email>kurta@linkedin.com</email>
      </address>
    </author>
```

There is no way for us to tell this is not a person, because it has `initials` and `surname`.

Can I propose the correct outcome to be the following?
```yaml
    name:
      given:
        formatted_initials:
          content: .
          language:
          - en
      surname:
        content: OAR-DEV Group
        language:
        - en
```

Adjustments welcome.

**Comment by strogonoff** [comment]
> There's not even a name inside this block:
> 
> ```yaml
>     name:
>       given:
>         formatted_initials:
>           language:
>           - en
>       surname:
>         content: None
>         language:
>         - en
>       completename:
>         content: None
>         language:
>         - en
> ```

@ronaldtse I did raise the issue only about the schema deliberately. Schema mismatch may break data loaders/deserializers (also raises the question as to how did this pass through serialization mechanism without failures, apparently some code doesn’t validate that `formatted_initials` is a valid formatted string?)

Unlike the schema, the issue with the _data_ is separate, it doesn’t break anything and can be fixed at any time…

But if we are talking about data, why do you include given name and `formatted_initials`  in your output since it seems like you only put there a full stop as a placeholder? I think it can be omitted and we could just have `surname` and `completename` left.

```
      given:
        formatted_initials:
          content: .
          language:
          - en
```
