### ISSUE TITLE
(URGENT) Wrong initials for "Julian F. Reschke"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#109]
From https://github.com/ietf-tools/bibxml-service/issues/315

Case 1:
https://github.com/relaton/relaton-data-ids/blob/f858737953940aeeae36fb483a73cbcb4aa14a85/data/draft-iab-xml2rfcv2-02.yaml#L25-L44

Case 2:
See also https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml
where it claims `<author fullname="Henrik Levkowetz" surname="Henrik Levkowetz">`

**Comment by strogonoff** [comment]
I think a more correct title/description would be that surname/forename are parsed incorrectly, this seems to describe the entire problem. Don’t see issues with initials per se.

**Comment by andrew2net** [comment]
fixed in v 1.13.6
https://github.com/relaton/relaton-data-ids/blob/cf393c63696d3bb987a0647246ee0ef9a898437d/data/draft-iab-xml2rfcv2-02.yaml#L25-L47
https://github.com/relaton/relaton-data-ids/blob/cf393c63696d3bb987a0647246ee0ef9a898437d/data/draft-levkowetz-xml2rfc-v3-implementation-notes-13.yaml#L27-L40

**Comment by ronaldtse** [comment]
The resulting data is incorrect as reported in https://github.com/ietf-tools/bibxml-service/issues/315#issuecomment-1324327678

These entries are directly obtained from Datatracker, and we should follow the name structures provided:

From:
https://datatracker.ietf.org/doc/bibxml3/reference.I-D.iab-xml2rfcv2.xml
```xml
<author initials="J." surname="Reschke" fullname="Julian Reschke">
```
=>
```yaml
contributor:
- person:
    name:
      given:
        forename:
        - content: Julian
          language:
          - en
        formatted_initials:
          content: J.
          language:
          - en
      surname:
        content: Reschke
        language:
        - en
      completename:
        content: Julian Reschke
        language:
        - en
```
