### ISSUE TITLE
(URGENT) Adopt new name model in Relaton for IETF documents

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#99]
Due to:
* https://github.com/ietf-tools/bibxml-service/issues/238
* https://github.com/ietf-tools/bibxml-service/issues/264

The situation:
1. The authoritative data from rfc-editor.org contains only the full name (i.e. "S. Bradner" here). The BibXML service is required to parse this single string into the `fullname` and `initials` attributes.
2. It is up to the XML RFC format on what goes into the `initials` attribute. Typically, it is the full name minus the surname. 

The RPC (as per @lbartholomew-rpc), requires the `initials` attribute to provide the "fully-formatted version of the initials of given names" as given by the RFC Editor.

i.e. 
* if the original was "S P", then `initials="S P"` (no dots)
* if the original was "S.P.", then `initials="S.P."` (with dots)
* if the original was "S P.", then `initials="S P."` (space then dot).

The intention is well said by @strogonoff :
> basically, we need to distinguish between canonical name ("complete name" now) and name properties used for various sorting and compatibility purposes

We need to update the Relaton name model to support this:
```yaml
- person:
  name:
    given:
      initials: J.P.
      components:
      - initial: J
      - initial: P    
    surname:
      content: Lang
    completename:
      content: J.P. Lang
```

From @andrew2net :
> To implement this in the Relaton model we need to update grammar first. The relaton-bib tests it's XML output against the grammar, so the tests will fail without the grammar changing

@strogonoff please track this issue to update your work at https://github.com/ietf-tools/bibxml-service/pull/263

**Comment by opoudjis** [comment]
Whatever I do, it will NOT follow that YAML. That YAML breaks backward compatibility.

**Comment by ronaldtse** [comment]
Whatever you propose, please make sure it satisfies the requirements.

**Comment by opoudjis** [comment]
The grammar currently is:

`( prefix*, forename*, initial*, surname, addition* ) | completeName`

Where `initial` is, as above, an individual initial letter, but which has been used rather loosely to date.

This shall become:

`( prefix*, forename*, initial*, formatted-initials?, surname, addition* ) | completeName`

Where `formatted-initials` takes the place of "initials" above.

**Comment by andrew2net** [comment]
> `( prefix*, forename*, initial*, formatted-initials?, surname, addition* ) | completeName`
> 
> Where `formatted-initials` takes the place of "initials" above.

@ronaldtse @ronaldtse looks good to me

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis  there is a problem: the `initial` element is a `LocalizedString` object, which can have attributes and is rendered as:
```yaml
initial:
  - content: A.
    language:
    - en
    script:
    - Latn
```
if we put initials into YAML as:
```yaml
- person:
  name:
    given:
      initials: J.P.
      components:
      - initial: J
      - initial: P    
```
we will lose the attributes. We should use this schema:
```yaml
- person:
  name:
    given:
      initials:
        content: J.P.
        language:
        - en
        script:
        - Latn
      components:
      - initial:
          content: J
          language:
          - en
          script:
          - Latn
      - initial:
          content: P
          language:
          - en
          script:
          - Latn
```
or change the type of `initial` to `String`.

**Comment by opoudjis** [comment]
No. Initials can be dropped or not given for all forenames, and we do need initials to be traced to forenames, for scenarios such as complete first name, initial for middle name. So we will make initial be an attribute of forename, which is a breaking change.

````
FullNameType = 
    (( prefix*, forename*, formatted-initials?, surname, addition* ) | completeName ),
    biblionote*, variantname*

prefix = element prefix { LocalizedString }
formatted-initials = element formatted-initials { LocalizedString }
addition = element addition { LocalizedString }
surname = element surname { LocalizedString }
forename = element forename {
  attribute initial { text }?,
  LocalizedString
}
completeName = element completename { LocalizedString }
````

**Comment by opoudjis** [comment]
> @ronaldtse @opoudjis there is a problem: the `initial` element is a `LocalizedString` object, which can have attributes and is rendered as:
> 
> ```yaml
> initial:
>   - content: A.
>     language:
>     - en
>     script:
>     - Latn
> ```
> 
> if we put initials into YAML as:
> 
> ```yaml
> - person:
>   name:
>     given:
>       initials: J.P.
>       components:
>       - initial: J
>       - initial: P    
> ```
> 
> we will lose the attributes. We should use this schema:
> 
> ```yaml
> - person:
>   name:
>     given:
>       initials:
>         content: J.P.
>         language:
>         - en
>         script:
>         - Latn
>       components:
>       - initial:
>           content: J
>           language:
>           - en
>           script:
>           - Latn
>       - initial:
>           content: P
>           language:
>           - en
>           script:
>           - Latn
> ```
> 
> or change the type of `initial` to `String`.

You're right. The initial is no longer a localised string: we're introducing too much complexity already for an edge case (because the real way to handle any complexity in initials is formatted-initials. They become strings.

**Comment by ronaldtse** [comment]
Thank you guys. The model changes have been made by @opoudjis here:
https://github.com/relaton/relaton-models/pull/42

@strogonoff @stefanomunarini needs to know the upcoming change of the Relaton format for IETF for relaton-py. Task filed at: https://github.com/relaton/relaton-py/issues/39

**Comment by andrew2net** [comment]
> No. Initials can be dropped or not given for all forenames, and we do need initials to be traced to forenames, for scenarios such as complete first name, initial for middle name. So we will make initial be an attribute of forename, which is a breaking change.
> 
> ```
> FullNameType = 
>     (( prefix*, forename*, formatted-initials?, surname, addition* ) | completeName ),
>     biblionote*, variantname*
> 
> prefix = element prefix { LocalizedString }
> formatted-initials = element formatted-initials { LocalizedString }
> addition = element addition { LocalizedString }
> surname = element surname { LocalizedString }
> forename = element forename {
>   attribute initial { text }?,
>   LocalizedString
> }
> completeName = element completename { LocalizedString }
> ```

@opoudjis we do not always have a forename. It's possible that we only have surname and initials. How can we use the forename's attribute to store an initial if we don't have mandatory content?

**Comment by opoudjis** [comment]
... We are going to use formatted-initials in that case. And actually... in the hypothetical you suggest, we could always mark it up as `<forename initial="B"/>`

**Comment by andrew2net** [comment]
@ronaldtse so the YAML will be:
```yaml
- person:
  name:
    given:
      initials:
        content: J.P.
        language:
        - en
        script:
        - Latn
      forename:
      - initial: J
        content: Jhon
      - initial: P
      - Jhonny
    surname: Lang
    completename: J.P. Lang
```
In case language and scrip are not given for `initials`, `initial`, `surname`, and `completename` they are just String.
Is it ok?

**Comment by ronaldtse** [comment]
I thought we are using the `formatted-initials` name? (I omitted `language` and `script` for simplicity)

```yaml
- person:
  name:
    formatted-initials:
      content: J.P.
    forename:
    - initial: J
      content: Jhon
    - initial: P
    - content: Jhonny
    surname: Lang
    completename: J.P. Lang
```

**Comment by andrew2net** [comment]
> I thought we are using the `formatted-initials` name? (I omitted `language` and `script` for simplicity)

@ronaldtse yes, you are right, we using `formatted-initials`
And I asked about using string, not object if `initial`, `language`, and `script` aren't given. For example:
```yaml
# no initial is given
forename:
  - Jhon

# initial is given
forename:
  - initial: J
    content: Jhon
```
The localizedString is used a lot across the Relaton model. In many cases, we don't have data for `language` and `script` attributes, so the YAML output is polluted with `content` keys.

**Comment by ronaldtse** [comment]
> And I asked about using string, not object if initial, language, and script aren't given

I think it's fine but @strogonoff @stefanomunarini may complain about parsing a non-normalized representation.

**Comment by ronaldtse** [comment]
@andrew2net to facilitate moving forward, can we just normalize using the object style, and we can implement compatibility with a string value? As long as the bibxml-service can consume the data easily. Thanks.

**Comment by ronaldtse** [comment]
@andrew2net is this completed? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse it is

**Comment by ronaldtse** [comment]
Thanks @andrew2net !

**Comment by strogonoff** [comment]
> @strogonoff please track this issue to update your work at [ietf-tools/bibxml-service#263](https://github.com/ietf-tools/bibxml-service/pull/263)

Thanks @ronaldtse. This would have to be a separate issue concerning relaton-py.

- Might be worth pinging @stefanomunarini on such issues in future. Stefano took charge over BibXML service while I had availability issues earlier this month, and it turns out both of us ended up missing this update.
  -  Or perhaps we could create a role/team for BibXML service maintainers (which would be me and Stefano currently) and notify that team as a whole, if Github allows.
- We should definitely be more explicit about these changes. If a breaking data source change is required, it’s worth filing an issue in relaton-py repository to update data models. Generally we should try to enforce semver and avoid breaking changes between major versions.

**Comment by ronaldtse** [comment]
@andrew2net @strogonoff I am NOT seeing the changes in initials in the https://github.com/ietf-tools/relaton-data-rfcs repo:

<img width="690" alt="Screen Shot 2022-08-25 at 11 31 19 AM" src="https://user-images.githubusercontent.com/11865/186568297-28034b07-c414-41fc-bfc5-8e961d6d7051.png">

Simply speaking -- NO data structure changes has occurred. What is going on?

**Comment by strogonoff** [comment]
@ronaldtse  I didn’t inspect source data. I _assumed_ it changed or is about to be changed based on 1) the fact that this ticket was closed, and 2) this snippet in description that implies a change in data structure:

```
- person:
  name:
    given:
      initials: J.P.
      components:
      - initial: J
      - initial: P    
    surname:
      content: Lang
    completename:
      content: J.P. Lang
```

I believe it’s possible that Andrew made relevant changes but simply didn’t release a new gem version yet, or the GHA didn’t have a chance to run yet.
